### ISSUE TITLE
Spring Boot Starter Redis 已被标记为 (DEPRECATED)

### ISSUE THREAD

**Issue by zohar-soul** [dyc87112/SpringBoot-Learning#5]
使用的时候我发现gradle 拉取构建一直失败，
就去看了一下。
发现推荐使用org.springframework.data » spring-data-redis。

**Comment by dyc87112** [comment]
是Spring Boot的版本原因。每次版本都有调整过一些依赖，具体可以参见每次的Release Notes，比如：https://github.com/spring-projects/spring-boot/wiki/Spring-Boot-1.5-Release-Notes
