### ISSUE TITLE
Chapter1

### ISSUE THREAD

**Issue by RonnieLyu** [dyc87112/SpringBoot-Learning#64]
根pom.xml
依赖
        <dependency>
            <groupId>org.springframework.boot</groupId>
            <artifactId>spring-boot-starter-web</artifactId>
        </dependency>
以后可以不需要再依赖
		<dependency>
			<groupId>org.springframework.boot</groupId>
			<artifactId>spring-boot-starter</artifactId>
		</dependency>

**Comment by dyc87112** [comment]
那个是1.x版本需要的，1.x版本的教程已经没继续更新咯，可以多关注下2.x目录下的。

**Comment by RonnieLyu** [comment]
嗯呢
