### ISSUE TITLE
Chapter3-1-1 请求如果是json是否会更好一点

### ISSUE THREAD

**Issue by RonnieLyu** [dyc87112/SpringBoot-Learning#65]
Chapter3-1-1 中是Spring Boot构建RESTful API与单元测试，构造的请求是表单形式而返回的是json。如果请求是json是否会更好一点，可以增加请求为json的说明或者事例（采用RequestBody）。

**Comment by dyc87112** [comment]
3-1-1的例子做的比较早，后面前后端分离后用@RequestBody多一些。1.x版本的教程已经没继续更新咯，可以多关注下2.x目录下的。
