### ISSUE TITLE
多服务实例 启动冲突

### ISSUE THREAD

**Issue by zhonghuazhi** [dyc87112/SpringBoot-Learning#66]
https://github.com/dyc87112/SpringBoot-Learning/blob/2b01f8f044fa197d3438b29dfcd3e5f74cb920e7/2.x/chapter3-11/src/main/resources/application.properties#L6

按照Demo样例 可以实现单服务 使用 FlyWay 方式管理数据库脚本，但是在多服务下 使用FlyWay异常。原因是因为 A服务启动后，数据库中已经存在 flyway_schema_history 表，而 B服务在启动的时候 ，直接报错。 org.flywaydb.core.api.exception.FlywayValidateException: Validate failed: Migrations have failed validation

**Comment by dyc87112** [comment]
不同服务公用一个数据库，这样的设计本身就不太合理哦
