### ISSUE TITLE
3-7配置jdbcTempalte多数据源里的配置文件两个jdbcTemplate对象不会覆盖吗

### ISSUE THREAD

**Issue by hhf296095496** [dyc87112/SpringBoot-Learning#87]
@Bean
    public JdbcTemplate primaryJdbcTemplate(@Qualifier("primaryDataSource") DataSource primaryDataSource) {
        return new JdbcTemplate(primaryDataSource);
    }

    @Bean
    public JdbcTemplate secondaryJdbcTemplate(@Qualifier("secondaryDataSource") DataSource secondaryDataSource) {
        return new JdbcTemplate(secondaryDataSource);
    }

上面是配置文件里的代码，这样写不会覆盖吗，容器里毕竟只能有一个JdbcTemplate类型的对象

**Comment by xiaofeiahaha** [comment]
您好！我已收到的您的来信，并会尽早查收。————————————————————                                                葛晓飞

**Comment by liuhamglin** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。

**Comment by uncleCG** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by dyc87112** [comment]
不会覆盖，这两个@Bean名称不同，会默认取方法名来命名，一个是primaryJdbcTemplate，一个是secondaryJdbcTemplate

**Comment by uncleCG** [comment]
这是来自QQ邮箱的假期自动回复邮件。您好，我最近正在休假中，无法亲自回复您的邮件。我将在假期结束后，尽快给您回复。

**Comment by xiaofeiahaha** [comment]
您好！我已收到的您的来信，并会尽早查收。————————————————————                                                葛晓飞

**Comment by liuhamglin** [comment]
这是一封自动回复邮件。已经收到您的来信，我会尽快回复。
